#!/usr/bin/env python

import csv
import json
import sys
from datetime import datetime
import os
from os import path

try:
	tags_file, source_file, live_file, id_col, snapshots_dir = sys.argv[1:]
except:
	usage = "Usage: {} <tags-file.json> <source-file.csv> <live-file.csv> <id-column> <snapshots-dir/>" .format(sys.argv[0])
	print(usage, file=sys.stderr)
	sys.exit(4)

if not path.isdir(snapshots_dir):
	raise Exception("snapshots_dir is not a directory!")

source = csv.DictReader(open(source_file))
live = csv.DictReader(open(live_file))

our_fields = set(live.fieldnames) - set(source.fieldnames)

our_data = {}

for row in live:
	custom_tags = {}
	for field in our_fields:
		if row.get(field):
			custom_tags[field] = row[field]
	if custom_tags:
		our_data[row[id_col]] = custom_tags

print(our_data)

with open("{}.tmp".format(tags_file), 'w') as tags:
	tags.write(json.dumps(our_data, indent=2))
if path.exists(tags_file):
	(root, ext) = path.splitext(tags_file)
	now = datetime.utcnow().isoformat()
	os.rename(tags_file, path.join(snapshots_dir, "{}_{}{}".format(path.basename(root), now, ext)))
os.rename("{}.tmp".format(tags_file), tags_file)

with open("{}.tmp".format(live_file), 'w') as live:
	fields = source.fieldnames
	fields.extend(our_fields)
	writer = csv.DictWriter(live, fields, dialect='excel')
	writer.writeheader()
	for row in source:
		writer.writerow({**row, **(our_data.get(row[id_col]) or {})})
os.rename("{}.tmp".format(live_file), live_file)
